name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and test with Maven (H2 DB)
        run: mvn clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
